package com.anupam.search.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.DateFormat;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;

import java.time.LocalDate;
import java.util.List;

/**
 * Elasticsearch document model representing an article.
 * Mapped to the "articles" index with field-level type and analyzer configuration
 * for optimized full-text search and aggregation support.
 *
 * @author Anupam
 */
@Document(indexName = "articles")
public class Article {

    /** Unique Elasticsearch document identifier. */
    @Id
    private String id;

    /** Article title, analyzed with the standard analyzer for full-text search. */
    @Field(type = FieldType.Text, analyzer = "standard")
    private String title;

    /** Article body content, analyzed with the standard analyzer. */
    @Field(type = FieldType.Text, analyzer = "standard")
    private String content;

    /** Author name stored as a keyword for exact-match filtering and aggregations. */
    @Field(type = FieldType.Keyword)
    private String author;

    /** Tags stored as keywords for filtering and tag-cloud aggregations. */
    @Field(type = FieldType.Keyword)
    private List<String> tags;

    /** Publication date stored in ISO date format for range queries. */
    @Field(type = FieldType.Date, format = DateFormat.date)
    private LocalDate publishedAt;

    /**
     * Default no-arg constructor required by Spring Data Elasticsearch.
     */
    public Article() {
    }

    /**
     * Constructs an Article with all fields except ID (auto-generated by Elasticsearch).
     *
     * @param title       the article title
     * @param content     the article body content
     * @param author      the author name
     * @param tags        the list of tags associated with the article
     * @param publishedAt the publication date
     */
    public Article(String title, String content, String author, List<String> tags, LocalDate publishedAt) {
        this.title = title;
        this.content = content;
        this.author = author;
        this.tags = tags;
        this.publishedAt = publishedAt;
    }

    /**
     * Returns the document ID.
     *
     * @return the Elasticsearch document ID
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the document ID.
     *
     * @param id the Elasticsearch document ID
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Returns the article title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the article title.
     *
     * @param title the title to set
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the article content.
     *
     * @return the body content
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the article content.
     *
     * @param content the body content to set
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Returns the author name.
     *
     * @return the author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the author name.
     *
     * @param author the author to set
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Returns the list of tags.
     *
     * @return the tags
     */
    public List<String> getTags() {
        return tags;
    }

    /**
     * Sets the list of tags.
     *
     * @param tags the tags to set
     */
    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    /**
     * Returns the publication date.
     *
     * @return the published date
     */
    public LocalDate getPublishedAt() {
        return publishedAt;
    }

    /**
     * Sets the publication date.
     *
     * @param publishedAt the published date to set
     */
    public void setPublishedAt(LocalDate publishedAt) {
        this.publishedAt = publishedAt;
    }
}
