spring:
  application:
    name: spring-boot-kafka-streams

  kafka:
    bootstrap-servers: localhost:29092
    streams:
      application-id: payment-stream-processor
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

logging:
  level:
    org.apache.kafka.streams: INFO
    com.anupam.streams: DEBUG
