spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/basicsdb
    driver-class-name: org.postgresql.Driver
    username: basics
    password: basics123

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
