package com.anupam.contract.producer;

import com.anupam.contract.producer.controller.PaymentController;
import io.restassured.module.mockmvc.RestAssuredMockMvc;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.test.web.servlet.setup.StandaloneMockMvcBuilder;

/**
 * Abstract base class for producer-side contract verification tests.
 * Sets up RestAssured MockMvc with the PaymentController so that
 * Spring Cloud Contract generated tests can verify the producer
 * fulfills its contractual obligations.
 *
 * <p>Subclasses are auto-generated by Spring Cloud Contract Verifier
 * from contract definitions in the test resources.</p>
 *
 * @author Anupam
 */
@SpringBootTest
public abstract class BaseContractTest {

    @Autowired
    private PaymentController paymentController;

    /**
     * Configures RestAssured MockMvc with a standalone setup of the PaymentController
     * before each test. This allows contract tests to execute HTTP requests against
     * the controller without starting a full server.
     */
    @BeforeEach
    void setup() {
        // Build standalone MockMvc for the payment controller
        StandaloneMockMvcBuilder standaloneMockMvcBuilder =
                MockMvcBuilders.standaloneSetup(paymentController);
        // Configure RestAssured to use the standalone MockMvc instance
        RestAssuredMockMvc.standaloneSetup(standaloneMockMvcBuilder);
    }
}
